# Generated by Django 5.1.4 on 2025-03-10 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrionEngine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sustainability_level', models.CharField(blank=True, choices=[('Very Sustainable', 'Very Sustainable'), ('Somewhat Sustainable', 'Somewhat Sustainable'), ('Not Sustainable', 'Not Sustainable'), ("I don't know", "I don't know")], max_length=50, null=True)),
                ('eco_choices', models.CharField(blank=True, choices=[('Always', 'Always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=50, null=True)),
                ('biggest_challenge', models.CharField(blank=True, choices=[('Lack of knowledge', 'Lack of knowledge'), ('Sustainable products are expensive', 'Sustainable products are expensive'), ('No time', 'No time'), ("I don't think it's important", "I don't think it's important")], max_length=100, null=True)),
                ('purchase_preference', models.CharField(blank=True, choices=[('Very important', 'Very important'), ('Somewhat important', 'Somewhat important'), ('Not important', 'Not important')], max_length=50, null=True)),
                ('waste_reduction', models.CharField(blank=True, choices=[('Always', 'Always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=50, null=True)),
                ('energy_saving', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('Sometimes', 'Sometimes'), ('No', 'No')], max_length=50, null=True)),
                ('wants_tips', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('Maybe', 'Maybe'), ('No', 'No')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
