# Generated by Django 5.1.4 on 2025-04-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrionEngine', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default='2001-01-01'),
            preserve_default=False,
        ),
    ]
