# Generated by Django 5.1.4 on 2025-04-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrionEngine', '0004_customuser_region_customuser_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=20, null=True),
        ),
    ]
