# Generated by Django 5.1.4 on 2025-04-26 20:21

import OrionEngine.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrionEngine', '0005_customuser_gender'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', OrionEngine.models.CustomUserManager()),
            ],
        ),
    ]
